name: SnakeGame
version: ${version}
main: ru.kirushkinx.snakegame.SnakeGamePlugin
api-version: '1.21'
author: kirushkinx
description: Classic snake game inside a cubistic game :D
dependencies:
  server:
    packetevents:
      required: true
      load: BEFORE
      join-classpath: true
